# Default values for driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deploymentName: route-deployment
serviceName: route
appLabel: route
appName: route

replicaCount: 1

image:
  repository: lomojiki/uber-msa-route
  # Always, IfNotPresent, Never
  imagePullPolicy: Never
  tag: latest

containerPort: 8075

service:
  type: ClusterIP
  port: 8075
  targetPort: 8075

appname_enabled: true
profile_enabled: true # get profile from config server
config_enabled: true # get config server url.
#server_side_discovery_enabled: false
eureka_enabled: true
resourceserver_enabled: false # gateway server which only needs keycloak url.
#otel_enabled: true # grafana
#kafka_enabled: true