spring:
  application:
    name: user
#  cloud:
#    config:
#      import:
#        configserver:

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/db?currentSchema=user_schema&binaryTransfer=true&reWriteBatchedInserts=true
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql
      mode: always

logging:
  level:
    org.springframework.context: DEBUG
    com.example: DEBUG