spring:
  application:
    name: "gateway"
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "default"
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
      resourceserver:
        jwt:
          jwk-set-uri: "https://www.googleapis.com/oauth2/v3/cert"
          issuer-uri: "https://accounts.google.com"

#    kubernetes:
#      discovery:
#        enabled: true
#        # Q. what if this is not true?
#        all-namespace: true



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gateway"
    description: "Uber Gateway"
    version: "1.0.0"


logging:
  level:
    com.example.gateway: INFO
    org.springframework.cloud.gateway: TRACE

