apiVersion: v2
name: infra-prod-env
description: A Helm chart to deploy multiple subcharts as a single release

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: user-db
    version: "0.1.0"
    repository: file://../../infra/db/user-db
  - name: order-db
    version: "0.1.0"
    repository: file://../../infra/db/order-db
