spring:
  application:
    name: "gateway"
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "default"
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
#    kubernetes:
#      discovery:
#        enabled: true
#        # Q. what if this is not true?
#        all-namespace: true


  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/db?currentSchema=user_schema&binaryTransfer=true&reWriteBatchedInserts=true
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql
      mode: always


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gateway"
    description: "Uber Gateway"
    version: "1.0.0"


logging:
  level:
    com.example.gateway: DEBUG