retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000


spring:
  jpa:
    #TODO: none 으로 설정해야 init-x.sql 스크립트로 실행된 테이블이 drop 안된다.
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        # show_sql: true
        default_schema: user_schema
        use_sql_comments: true
        format_sql: true
  database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=user_schema&binaryTransfer=true&reWriteBatchedInserts=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      #TODO: "mode: always + hibernate.ddl-auto: none" 로 설정해야 스크립트가 실행된다. hibernate.ddl-auto: none 과 같이.
      mode: always
      platform: postgres
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql