/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DriverMatchedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = -7144301576343018590L;


    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DriverMatchedEvent\",\"namespace\":\"com.example.kafka.avro.model\",\"fields\":[{\"name\":\"correlationId\",\"type\":\"string\"},{\"name\":\"status\",\"type\":\"string\"},{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"address\",\"type\":{\"type\":\"record\",\"name\":\"Address\",\"fields\":[{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"postalCode\",\"type\":\"string\"}]}},{\"name\":\"driverDetails\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DriverDetails\",\"fields\":[{\"name\":\"driverId\",\"type\":\"string\"},{\"name\":\"lat\",\"type\":\"double\"},{\"name\":\"lon\",\"type\":\"double\"}]}],\"default\":null},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<DriverMatchedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DriverMatchedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DriverMatchedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DriverMatchedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DriverMatchedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DriverMatchedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DriverMatchedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DriverMatchedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DriverMatchedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence correlationId;
    private java.lang.CharSequence status;
  private java.lang.CharSequence userId;
  private com.example.kafka.avro.model.Address address;
  private com.example.kafka.avro.model.DriverDetails driverDetails;
  private java.time.Instant createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DriverMatchedEvent() {
  }

  /**
   * All-args constructor.
   * @param correlationId The new value for correlationId
   * @param status The new value for status
   * @param userId The new value for userId
   * @param address The new value for address
   * @param driverDetails The new value for driverDetails
   * @param createdAt The new value for createdAt
   */
  public DriverMatchedEvent(java.lang.CharSequence correlationId, java.lang.CharSequence status, java.lang.CharSequence userId, com.example.kafka.avro.model.Address address, com.example.kafka.avro.model.DriverDetails driverDetails, java.time.Instant createdAt) {
    this.correlationId = correlationId;
      this.status = status;
    this.userId = userId;
    this.address = address;
    this.driverDetails = driverDetails;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() {
      return MODEL$;
  }

  @Override
  public org.apache.avro.Schema getSchema() {
      return SCHEMA$;
  }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
        case 0:
            return correlationId;
        case 1:
            return status;
        case 2:
            return userId;
        case 3:
            return address;
        case 4:
            return driverDetails;
        case 5:
            return createdAt;
        default:
            throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[]{
          null,
          null,
          null,
          null,
          null,
          new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
          null
      };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
        case 0:
            correlationId = (java.lang.CharSequence) value$;
            break;
        case 1:
            status = (java.lang.CharSequence) value$;
            break;
        case 2:
            userId = (java.lang.CharSequence) value$;
            break;
        case 3:
            address = (com.example.kafka.avro.model.Address) value$;
            break;
        case 4:
            driverDetails = (com.example.kafka.avro.model.DriverDetails) value$;
            break;
        case 5:
            createdAt = (java.time.Instant) value$;
            break;
        default:
            throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'correlationId' field.
   * @return The value of the 'correlationId' field.
   */
  public java.lang.CharSequence getCorrelationId() {
    return correlationId;
  }


  /**
   * Sets the value of the 'correlationId' field.
   * @param value the value to set.
   */
  public void setCorrelationId(java.lang.CharSequence value) {
    this.correlationId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
      return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
      this.status = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'address' field.
   * @return The value of the 'address' field.
   */
  public com.example.kafka.avro.model.Address getAddress() {
    return address;
  }


  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(com.example.kafka.avro.model.Address value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'driverDetails' field.
   * @return The value of the 'driverDetails' field.
   */
  public com.example.kafka.avro.model.DriverDetails getDriverDetails() {
    return driverDetails;
  }


  /**
   * Sets the value of the 'driverDetails' field.
   * @param value the value to set.
   */
  public void setDriverDetails(com.example.kafka.avro.model.DriverDetails value) {
    this.driverDetails = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new DriverMatchedEvent RecordBuilder.
   * @return A new DriverMatchedEvent RecordBuilder
   */
  public static com.example.kafka.avro.model.DriverMatchedEvent.Builder newBuilder() {
    return new com.example.kafka.avro.model.DriverMatchedEvent.Builder();
  }

  /**
   * Creates a new DriverMatchedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DriverMatchedEvent RecordBuilder
   */
  public static com.example.kafka.avro.model.DriverMatchedEvent.Builder newBuilder(com.example.kafka.avro.model.DriverMatchedEvent.Builder other) {
    if (other == null) {
      return new com.example.kafka.avro.model.DriverMatchedEvent.Builder();
    } else {
      return new com.example.kafka.avro.model.DriverMatchedEvent.Builder(other);
    }
  }

  /**
   * Creates a new DriverMatchedEvent RecordBuilder by copying an existing DriverMatchedEvent instance.
   * @param other The existing instance to copy.
   * @return A new DriverMatchedEvent RecordBuilder
   */
  public static com.example.kafka.avro.model.DriverMatchedEvent.Builder newBuilder(com.example.kafka.avro.model.DriverMatchedEvent other) {
    if (other == null) {
      return new com.example.kafka.avro.model.DriverMatchedEvent.Builder();
    } else {
      return new com.example.kafka.avro.model.DriverMatchedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for DriverMatchedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DriverMatchedEvent>
      implements org.apache.avro.data.RecordBuilder<DriverMatchedEvent> {

    private java.lang.CharSequence correlationId;
      private java.lang.CharSequence status;
    private java.lang.CharSequence userId;
    private com.example.kafka.avro.model.Address address;
    private com.example.kafka.avro.model.Address.Builder addressBuilder;
    private com.example.kafka.avro.model.DriverDetails driverDetails;
    private com.example.kafka.avro.model.DriverDetails.Builder driverDetailsBuilder;
    private java.time.Instant createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.kafka.avro.model.DriverMatchedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[0].schema(), other.correlationId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
        if (isValidValue(fields()[1], other.status)) {
            this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.address)) {
        this.address = data().deepCopy(fields()[3].schema(), other.address);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasAddressBuilder()) {
        this.addressBuilder = com.example.kafka.avro.model.Address.newBuilder(other.getAddressBuilder());
      }
      if (isValidValue(fields()[4], other.driverDetails)) {
        this.driverDetails = data().deepCopy(fields()[4].schema(), other.driverDetails);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasDriverDetailsBuilder()) {
        this.driverDetailsBuilder = com.example.kafka.avro.model.DriverDetails.newBuilder(other.getDriverDetailsBuilder());
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing DriverMatchedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.kafka.avro.model.DriverMatchedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[0].schema(), other.correlationId);
        fieldSetFlags()[0] = true;
      }
        if (isValidValue(fields()[1], other.status)) {
            this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.address)) {
        this.address = data().deepCopy(fields()[3].schema(), other.address);
        fieldSetFlags()[3] = true;
      }
      this.addressBuilder = null;
      if (isValidValue(fields()[4], other.driverDetails)) {
        this.driverDetails = data().deepCopy(fields()[4].schema(), other.driverDetails);
        fieldSetFlags()[4] = true;
      }
      this.driverDetailsBuilder = null;
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = true;
      }
    }

    /**
     * Gets the value of the 'correlationId' field.
     * @return The value.
     */
    public java.lang.CharSequence getCorrelationId() {
      return correlationId;
    }


    /**
     * Sets the value of the 'correlationId' field.
     * @param value The value of 'correlationId'.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverMatchedEvent.Builder setCorrelationId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.correlationId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'correlationId' field has been set.
     * @return True if the 'correlationId' field has been set, false otherwise.
     */
    public boolean hasCorrelationId() {
      return fieldSetFlags()[0];
    }


    /**
     * Clears the value of the 'correlationId' field.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverMatchedEvent.Builder clearCorrelationId() {
      correlationId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'status' field.
     * @return The value.
     */
    public java.lang.CharSequence getStatus() {
        return status;
    }


    /**
     * Sets the value of the 'status' field.
     * @param value The value of 'status'.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverMatchedEvent.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[1], value);
        this.status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'status' field has been set.
     * @return True if the 'status' field has been set, false otherwise.
     */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
     * Clears the value of the 'status' field.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverMatchedEvent.Builder clearStatus() {
        status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'userId' field.
     * @return The value.
     */
    public java.lang.CharSequence getUserId() {
      return userId;
    }


    /**
     * Sets the value of the 'userId' field.
     * @param value The value of 'userId'.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverMatchedEvent.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.userId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'userId' field has been set.
     * @return True if the 'userId' field has been set, false otherwise.
     */
    public boolean hasUserId() {
      return fieldSetFlags()[2];
    }


    /**
     * Clears the value of the 'userId' field.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverMatchedEvent.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
     * Gets the value of the 'address' field.
     * @return The value.
     */
    public com.example.kafka.avro.model.Address getAddress() {
      return address;
    }


    /**
     * Sets the value of the 'address' field.
     * @param value The value of 'address'.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverMatchedEvent.Builder setAddress(com.example.kafka.avro.model.Address value) {
      validate(fields()[3], value);
      this.addressBuilder = null;
      this.address = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
     * Checks whether the 'address' field has been set.
     * @return True if the 'address' field has been set, false otherwise.
     */
    public boolean hasAddress() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'address' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.example.kafka.avro.model.Address.Builder getAddressBuilder() {
      if (addressBuilder == null) {
        if (hasAddress()) {
          setAddressBuilder(com.example.kafka.avro.model.Address.newBuilder(address));
        } else {
          setAddressBuilder(com.example.kafka.avro.model.Address.newBuilder());
        }
      }
      return addressBuilder;
    }

    /**
     * Sets the Builder instance for the 'address' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.example.kafka.avro.model.DriverMatchedEvent.Builder setAddressBuilder(com.example.kafka.avro.model.Address.Builder value) {
      clearAddress();
      addressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'address' field has an active Builder instance
     * @return True if the 'address' field has an active Builder instance
     */
    public boolean hasAddressBuilder() {
      return addressBuilder != null;
    }

    /**
     * Clears the value of the 'address' field.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverMatchedEvent.Builder clearAddress() {
      address = null;
      addressBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
     * Gets the value of the 'driverDetails' field.
     * @return The value.
     */
    public com.example.kafka.avro.model.DriverDetails getDriverDetails() {
      return driverDetails;
    }


    /**
     * Sets the value of the 'driverDetails' field.
     * @param value The value of 'driverDetails'.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverMatchedEvent.Builder setDriverDetails(com.example.kafka.avro.model.DriverDetails value) {
      validate(fields()[4], value);
      this.driverDetailsBuilder = null;
      this.driverDetails = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
     * Checks whether the 'driverDetails' field has been set.
     * @return True if the 'driverDetails' field has been set, false otherwise.
     */
    public boolean hasDriverDetails() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'driverDetails' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverDetails.Builder getDriverDetailsBuilder() {
      if (driverDetailsBuilder == null) {
        if (hasDriverDetails()) {
          setDriverDetailsBuilder(com.example.kafka.avro.model.DriverDetails.newBuilder(driverDetails));
        } else {
          setDriverDetailsBuilder(com.example.kafka.avro.model.DriverDetails.newBuilder());
        }
      }
      return driverDetailsBuilder;
    }

    /**
     * Sets the Builder instance for the 'driverDetails' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.example.kafka.avro.model.DriverMatchedEvent.Builder setDriverDetailsBuilder(com.example.kafka.avro.model.DriverDetails.Builder value) {
      clearDriverDetails();
      driverDetailsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'driverDetails' field has an active Builder instance
     * @return True if the 'driverDetails' field has an active Builder instance
     */
    public boolean hasDriverDetailsBuilder() {
      return driverDetailsBuilder != null;
    }

    /**
     * Clears the value of the 'driverDetails' field.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverMatchedEvent.Builder clearDriverDetails() {
      driverDetails = null;
      driverDetailsBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
     * Gets the value of the 'createdAt' field.
     * @return The value.
     */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
     * Sets the value of the 'createdAt' field.
     * @param value The value of 'createdAt'.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverMatchedEvent.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[5], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
     * Checks whether the 'createdAt' field has been set.
     * @return True if the 'createdAt' field has been set, false otherwise.
     */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[5];
    }


    /**
     * Clears the value of the 'createdAt' field.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverMatchedEvent.Builder clearCreatedAt() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DriverMatchedEvent build() {
      try {
        DriverMatchedEvent record = new DriverMatchedEvent();
        record.correlationId = fieldSetFlags()[0] ? this.correlationId : (java.lang.CharSequence) defaultValue(fields()[0]);
          record.status = fieldSetFlags()[1] ? this.status : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.userId = fieldSetFlags()[2] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[2]);
        if (addressBuilder != null) {
          try {
            record.address = this.addressBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("address"));
            throw e;
          }
        } else {
          record.address = fieldSetFlags()[3] ? this.address : (com.example.kafka.avro.model.Address) defaultValue(fields()[3]);
        }
        if (driverDetailsBuilder != null) {
          try {
            record.driverDetails = this.driverDetailsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("driverDetails"));
            throw e;
          }
        } else {
          record.driverDetails = fieldSetFlags()[4] ? this.driverDetails : (com.example.kafka.avro.model.DriverDetails) defaultValue(fields()[4]);
        }
        record.createdAt = fieldSetFlags()[5] ? this.createdAt : (java.time.Instant) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DriverMatchedEvent>
      WRITER$ = (org.apache.avro.io.DatumWriter<DriverMatchedEvent>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out)
        throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DriverMatchedEvent>
      READER$ = (org.apache.avro.io.DatumReader<DriverMatchedEvent>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in)
        throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










