/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.example.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DriverDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3157377054708911381L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DriverDetails\",\"namespace\":\"com.example.kafka.avro.model\",\"fields\":[{\"name\":\"driverId\",\"type\":\"string\"},{\"name\":\"lat\",\"type\":\"double\"},{\"name\":\"lon\",\"type\":\"double\"}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DriverDetails> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DriverDetails> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DriverDetails> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DriverDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DriverDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DriverDetails to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DriverDetails from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DriverDetails instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DriverDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence driverId;
  private double lat;
  private double lon;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DriverDetails() {
  }

  /**
   * All-args constructor.
   * @param driverId The new value for driverId
   * @param lat The new value for lat
   * @param lon The new value for lon
   */
  public DriverDetails(java.lang.CharSequence driverId, java.lang.Double lat, java.lang.Double lon) {
    this.driverId = driverId;
    this.lat = lat;
    this.lon = lon;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  @Override
  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return driverId;
      case 1:
        return lat;
      case 2:
        return lon;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        driverId = (java.lang.CharSequence) value$;
        break;
      case 1:
        lat = (java.lang.Double) value$;
        break;
      case 2:
        lon = (java.lang.Double) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'driverId' field.
   * @return The value of the 'driverId' field.
   */
  public java.lang.CharSequence getDriverId() {
    return driverId;
  }


  /**
   * Sets the value of the 'driverId' field.
   * @param value the value to set.
   */
  public void setDriverId(java.lang.CharSequence value) {
    this.driverId = value;
  }

  /**
   * Gets the value of the 'lat' field.
   * @return The value of the 'lat' field.
   */
  public double getLat() {
    return lat;
  }


  /**
   * Sets the value of the 'lat' field.
   * @param value the value to set.
   */
  public void setLat(double value) {
    this.lat = value;
  }

  /**
   * Gets the value of the 'lon' field.
   * @return The value of the 'lon' field.
   */
  public double getLon() {
    return lon;
  }


  /**
   * Sets the value of the 'lon' field.
   * @param value the value to set.
   */
  public void setLon(double value) {
    this.lon = value;
  }

  /**
   * Creates a new DriverDetails RecordBuilder.
   * @return A new DriverDetails RecordBuilder
   */
  public static com.example.kafka.avro.model.DriverDetails.Builder newBuilder() {
    return new com.example.kafka.avro.model.DriverDetails.Builder();
  }

  /**
   * Creates a new DriverDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DriverDetails RecordBuilder
   */
  public static com.example.kafka.avro.model.DriverDetails.Builder newBuilder(com.example.kafka.avro.model.DriverDetails.Builder other) {
    if (other == null) {
      return new com.example.kafka.avro.model.DriverDetails.Builder();
    } else {
      return new com.example.kafka.avro.model.DriverDetails.Builder(other);
    }
  }

  /**
   * Creates a new DriverDetails RecordBuilder by copying an existing DriverDetails instance.
   * @param other The existing instance to copy.
   * @return A new DriverDetails RecordBuilder
   */
  public static com.example.kafka.avro.model.DriverDetails.Builder newBuilder(com.example.kafka.avro.model.DriverDetails other) {
    if (other == null) {
      return new com.example.kafka.avro.model.DriverDetails.Builder();
    } else {
      return new com.example.kafka.avro.model.DriverDetails.Builder(other);
    }
  }

  /**
   * RecordBuilder for DriverDetails instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DriverDetails>
      implements org.apache.avro.data.RecordBuilder<DriverDetails> {

    private java.lang.CharSequence driverId;
    private double lat;
    private double lon;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.kafka.avro.model.DriverDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.driverId)) {
        this.driverId = data().deepCopy(fields()[0].schema(), other.driverId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.lat)) {
        this.lat = data().deepCopy(fields()[1].schema(), other.lat);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.lon)) {
        this.lon = data().deepCopy(fields()[2].schema(), other.lon);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing DriverDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.kafka.avro.model.DriverDetails other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.driverId)) {
        this.driverId = data().deepCopy(fields()[0].schema(), other.driverId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lat)) {
        this.lat = data().deepCopy(fields()[1].schema(), other.lat);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lon)) {
        this.lon = data().deepCopy(fields()[2].schema(), other.lon);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Gets the value of the 'driverId' field.
     * @return The value.
     */
    public java.lang.CharSequence getDriverId() {
      return driverId;
    }


    /**
     * Sets the value of the 'driverId' field.
     * @param value The value of 'driverId'.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverDetails.Builder setDriverId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.driverId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'driverId' field has been set.
     * @return True if the 'driverId' field has been set, false otherwise.
     */
    public boolean hasDriverId() {
      return fieldSetFlags()[0];
    }


    /**
     * Clears the value of the 'driverId' field.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverDetails.Builder clearDriverId() {
      driverId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'lat' field.
     * @return The value.
     */
    public double getLat() {
      return lat;
    }


    /**
     * Sets the value of the 'lat' field.
     * @param value The value of 'lat'.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverDetails.Builder setLat(double value) {
      validate(fields()[1], value);
      this.lat = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'lat' field has been set.
     * @return True if the 'lat' field has been set, false otherwise.
     */
    public boolean hasLat() {
      return fieldSetFlags()[1];
    }


    /**
     * Clears the value of the 'lat' field.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverDetails.Builder clearLat() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'lon' field.
     * @return The value.
     */
    public double getLon() {
      return lon;
    }


    /**
     * Sets the value of the 'lon' field.
     * @param value The value of 'lon'.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverDetails.Builder setLon(double value) {
      validate(fields()[2], value);
      this.lon = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'lon' field has been set.
     * @return True if the 'lon' field has been set, false otherwise.
     */
    public boolean hasLon() {
      return fieldSetFlags()[2];
    }


    /**
     * Clears the value of the 'lon' field.
     * @return This builder.
     */
    public com.example.kafka.avro.model.DriverDetails.Builder clearLon() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DriverDetails build() {
      try {
        DriverDetails record = new DriverDetails();
        record.driverId = fieldSetFlags()[0] ? this.driverId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.lat = fieldSetFlags()[1] ? this.lat : (java.lang.Double) defaultValue(fields()[1]);
        record.lon = fieldSetFlags()[2] ? this.lon : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DriverDetails>
      WRITER$ = (org.apache.avro.io.DatumWriter<DriverDetails>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out)
      throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DriverDetails>
      READER$ = (org.apache.avro.io.DatumReader<DriverDetails>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in)
      throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override
  protected boolean hasCustomCoders() {
    return true;
  }

  @Override
  public void customEncode(org.apache.avro.io.Encoder out)
      throws java.io.IOException {
    out.writeString(this.driverId);

    out.writeDouble(this.lat);

    out.writeDouble(this.lon);

  }

  @Override
  public void customDecode(org.apache.avro.io.ResolvingDecoder in)
      throws java.io.IOException {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.driverId = in.readString(this.driverId instanceof Utf8 ? (Utf8) this.driverId : null);

      this.lat = in.readDouble();

      this.lon = in.readDouble();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
          case 0:
            this.driverId = in.readString(this.driverId instanceof Utf8 ? (Utf8) this.driverId : null);
            break;

          case 1:
            this.lat = in.readDouble();
            break;

          case 2:
            this.lon = in.readDouble();
            break;

          default:
            throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










