/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.example.kafka.avro.model;

@org.apache.avro.specific.AvroGenerated
public enum NotificationType implements org.apache.avro.generic.GenericEnumSymbol<NotificationType> {
    ORDER_APPROVED, DRIVER_MATCHED, ORDER_CANCELLED, DRIVER_ARRIVED;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NotificationType\",\"namespace\":\"com.example.kafka.avro.model\",\"symbols\":[\"ORDER_APPROVED\",\"DRIVER_MATCHED\",\"ORDER_CANCELLED\",\"DRIVER_ARRIVED\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    @Override
    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
