/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.kafka.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum OrderStatus implements org.apache.avro.generic.GenericEnumSymbol<OrderStatus> {
    CREATED, USER_CANCELLED, PAYMENT_COMPLETED, PAYMENT_CANCELLED, RESTAURANT_APPROVED, RESTAURANT_REJECTED;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderStatus\",\"namespace\":\"com.example.kafka.avro.model\",\"symbols\":[\"CREATED\",\"USER_CANCELLED\",\"PAYMENT_COMPLETED\",\"PAYMENT_CANCELLED\",\"RESTAURANT_APPROVED\",\"RESTAURANT_REJECTED\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

  @Override
  public org.apache.avro.Schema getSchema() {
      return SCHEMA$;
  }
}
