/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ResponseAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = -5403843991489033270L;


    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ResponseAvroModel\",\"namespace\":\"com.example.kafka.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"sagaId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"paymentId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"callerId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"callId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"calleeId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"price\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"orderStatus\",\"type\":{\"type\":\"enum\",\"name\":\"OrderStatus\",\"symbols\":[\"PENDING\",\"CALLER_CANCELLED\",\"PAYMENT_COMPLETED\",\"PAYMENT_CANCELLED\",\"CALLEE_APPROVED\",\"CALLEE_REJECTED\"]}},{\"name\":\"failureMessages\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

    private static final SpecificData MODEL$ = new SpecificData();

    static {
        MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<ResponseAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ResponseAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ResponseAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ResponseAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ResponseAvroModel> createDecoder(SchemaStore resolver) {
      return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ResponseAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ResponseAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ResponseAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ResponseAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

    private java.util.UUID id;
    private java.util.UUID sagaId;
    private java.util.UUID paymentId;
    private java.util.UUID callerId;
    private java.util.UUID callId;
    private java.util.UUID calleeId;
    private java.nio.ByteBuffer price;
    private java.time.Instant createdAt;
    private com.example.kafka.avro.model.OrderStatus orderStatus;
    private java.lang.CharSequence failureMessages;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ResponseAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param sagaId The new value for sagaId
   * @param paymentId The new value for paymentId
   * @param callerId The new value for callerId
   * @param callId The new value for callId
   * @param calleeId The new value for calleeId
   * @param price The new value for price
   * @param createdAt The new value for createdAt
   * @param orderStatus The new value for orderStatus
   * @param failureMessages The new value for failureMessages
   */
  public ResponseAvroModel(java.util.UUID id, java.util.UUID sagaId, java.util.UUID paymentId, java.util.UUID callerId, java.util.UUID callId, java.util.UUID calleeId, java.nio.ByteBuffer price, java.time.Instant createdAt, com.example.kafka.avro.model.OrderStatus orderStatus, java.lang.CharSequence failureMessages) {
    this.id = id;
    this.sagaId = sagaId;
    this.paymentId = paymentId;
    this.callerId = callerId;
    this.callId = callId;
    this.calleeId = calleeId;
    this.price = price;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      this.orderStatus = orderStatus;
    this.failureMessages = failureMessages;
  }

    @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

    @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return sagaId;
    case 2: return paymentId;
    case 3: return callerId;
    case 4: return callId;
    case 5: return calleeId;
    case 6: return price;
    case 7: return createdAt;
        case 8:
            return orderStatus;
    case 9: return failureMessages;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
          new org.apache.avro.Conversions.UUIDConversion(),
          new org.apache.avro.Conversions.UUIDConversion(),
          new org.apache.avro.Conversions.UUIDConversion(),
          new org.apache.avro.Conversions.UUIDConversion(),
          new org.apache.avro.Conversions.UUIDConversion(),
          new org.apache.avro.Conversions.UUIDConversion(),
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
        case 0:
            id = (java.util.UUID) value$;
            break;
        case 1:
            sagaId = (java.util.UUID) value$;
            break;
        case 2:
            paymentId = (java.util.UUID) value$;
            break;
        case 3:
            callerId = (java.util.UUID) value$;
            break;
        case 4:
            callId = (java.util.UUID) value$;
            break;
        case 5:
            calleeId = (java.util.UUID) value$;
            break;
    case 6: price = (java.nio.ByteBuffer)value$; break;
    case 7: createdAt = (java.time.Instant)value$; break;
        case 8:
            orderStatus = (com.example.kafka.avro.model.OrderStatus) value$;
            break;
    case 9: failureMessages = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.util.UUID getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.util.UUID value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'sagaId' field.
   * @return The value of the 'sagaId' field.
   */
  public java.util.UUID getSagaId() {
    return sagaId;
  }


  /**
   * Sets the value of the 'sagaId' field.
   * @param value the value to set.
   */
  public void setSagaId(java.util.UUID value) {
    this.sagaId = value;
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.util.UUID getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.util.UUID value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'callerId' field.
   * @return The value of the 'callerId' field.
   */
  public java.util.UUID getCallerId() {
    return callerId;
  }


  /**
   * Sets the value of the 'callerId' field.
   * @param value the value to set.
   */
  public void setCallerId(java.util.UUID value) {
    this.callerId = value;
  }

  /**
   * Gets the value of the 'callId' field.
   * @return The value of the 'callId' field.
   */
  public java.util.UUID getCallId() {
    return callId;
  }


  /**
   * Sets the value of the 'callId' field.
   * @param value the value to set.
   */
  public void setCallId(java.util.UUID value) {
    this.callId = value;
  }

  /**
   * Gets the value of the 'calleeId' field.
   * @return The value of the 'calleeId' field.
   */
  public java.util.UUID getCalleeId() {
    return calleeId;
  }


  /**
   * Sets the value of the 'calleeId' field.
   * @param value the value to set.
   */
  public void setCalleeId(java.util.UUID value) {
    this.calleeId = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public java.nio.ByteBuffer getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.nio.ByteBuffer value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'orderStatus' field.
   * @return The value of the 'orderStatus' field.
   */
  public com.example.kafka.avro.model.OrderStatus getOrderStatus() {
      return orderStatus;
  }


  /**
   * Sets the value of the 'orderStatus' field.
   * @param value the value to set.
   */
  public void setOrderStatus(com.example.kafka.avro.model.OrderStatus value) {
      this.orderStatus = value;
  }

  /**
   * Gets the value of the 'failureMessages' field.
   * @return The value of the 'failureMessages' field.
   */
  public java.lang.CharSequence getFailureMessages() {
    return failureMessages;
  }


  /**
   * Sets the value of the 'failureMessages' field.
   * @param value the value to set.
   */
  public void setFailureMessages(java.lang.CharSequence value) {
    this.failureMessages = value;
  }

  /**
   * Creates a new ResponseAvroModel RecordBuilder.
   * @return A new ResponseAvroModel RecordBuilder
   */
  public static com.example.kafka.avro.model.ResponseAvroModel.Builder newBuilder() {
    return new com.example.kafka.avro.model.ResponseAvroModel.Builder();
  }

  /**
   * Creates a new ResponseAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ResponseAvroModel RecordBuilder
   */
  public static com.example.kafka.avro.model.ResponseAvroModel.Builder newBuilder(com.example.kafka.avro.model.ResponseAvroModel.Builder other) {
    if (other == null) {
      return new com.example.kafka.avro.model.ResponseAvroModel.Builder();
    } else {
      return new com.example.kafka.avro.model.ResponseAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new ResponseAvroModel RecordBuilder by copying an existing ResponseAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new ResponseAvroModel RecordBuilder
   */
  public static com.example.kafka.avro.model.ResponseAvroModel.Builder newBuilder(com.example.kafka.avro.model.ResponseAvroModel other) {
    if (other == null) {
      return new com.example.kafka.avro.model.ResponseAvroModel.Builder();
    } else {
      return new com.example.kafka.avro.model.ResponseAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for ResponseAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ResponseAvroModel>
    implements org.apache.avro.data.RecordBuilder<ResponseAvroModel> {

      private java.util.UUID id;
      private java.util.UUID sagaId;
      private java.util.UUID paymentId;
      private java.util.UUID callerId;
      private java.util.UUID callId;
      private java.util.UUID calleeId;
    private java.nio.ByteBuffer price;
    private java.time.Instant createdAt;
      private com.example.kafka.avro.model.OrderStatus orderStatus;
    private java.lang.CharSequence failureMessages;

    /** Creates a new Builder */
    private Builder() {
        super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.kafka.avro.model.ResponseAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[2].schema(), other.paymentId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.callerId)) {
        this.callerId = data().deepCopy(fields()[3].schema(), other.callerId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.callId)) {
        this.callId = data().deepCopy(fields()[4].schema(), other.callId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.calleeId)) {
        this.calleeId = data().deepCopy(fields()[5].schema(), other.calleeId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.price)) {
        this.price = data().deepCopy(fields()[6].schema(), other.price);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[7].schema(), other.createdAt);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
        if (isValidValue(fields()[8], other.orderStatus)) {
            this.orderStatus = data().deepCopy(fields()[8].schema(), other.orderStatus);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.failureMessages)) {
        this.failureMessages = data().deepCopy(fields()[9].schema(), other.failureMessages);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing ResponseAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.kafka.avro.model.ResponseAvroModel other) {
        super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[2].schema(), other.paymentId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.callerId)) {
        this.callerId = data().deepCopy(fields()[3].schema(), other.callerId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.callId)) {
        this.callId = data().deepCopy(fields()[4].schema(), other.callId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.calleeId)) {
        this.calleeId = data().deepCopy(fields()[5].schema(), other.calleeId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.price)) {
        this.price = data().deepCopy(fields()[6].schema(), other.price);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[7].schema(), other.createdAt);
        fieldSetFlags()[7] = true;
      }
        if (isValidValue(fields()[8], other.orderStatus)) {
            this.orderStatus = data().deepCopy(fields()[8].schema(), other.orderStatus);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.failureMessages)) {
        this.failureMessages = data().deepCopy(fields()[9].schema(), other.failureMessages);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.util.UUID getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder setId(java.util.UUID value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sagaId' field.
      * @return The value.
      */
    public java.util.UUID getSagaId() {
      return sagaId;
    }


    /**
      * Sets the value of the 'sagaId' field.
      * @param value The value of 'sagaId'.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder setSagaId(java.util.UUID value) {
      validate(fields()[1], value);
      this.sagaId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sagaId' field has been set.
      * @return True if the 'sagaId' field has been set, false otherwise.
      */
    public boolean hasSagaId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sagaId' field.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder clearSagaId() {
      sagaId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.util.UUID getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder setPaymentId(java.util.UUID value) {
      validate(fields()[2], value);
      this.paymentId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'callerId' field.
      * @return The value.
      */
    public java.util.UUID getCallerId() {
      return callerId;
    }


    /**
      * Sets the value of the 'callerId' field.
      * @param value The value of 'callerId'.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder setCallerId(java.util.UUID value) {
      validate(fields()[3], value);
      this.callerId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'callerId' field has been set.
      * @return True if the 'callerId' field has been set, false otherwise.
      */
    public boolean hasCallerId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'callerId' field.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder clearCallerId() {
      callerId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'callId' field.
      * @return The value.
      */
    public java.util.UUID getCallId() {
      return callId;
    }


    /**
      * Sets the value of the 'callId' field.
      * @param value The value of 'callId'.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder setCallId(java.util.UUID value) {
      validate(fields()[4], value);
      this.callId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'callId' field has been set.
      * @return True if the 'callId' field has been set, false otherwise.
      */
    public boolean hasCallId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'callId' field.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder clearCallId() {
      callId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'calleeId' field.
      * @return The value.
      */
    public java.util.UUID getCalleeId() {
      return calleeId;
    }


    /**
      * Sets the value of the 'calleeId' field.
      * @param value The value of 'calleeId'.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder setCalleeId(java.util.UUID value) {
      validate(fields()[5], value);
      this.calleeId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'calleeId' field has been set.
      * @return True if the 'calleeId' field has been set, false otherwise.
      */
    public boolean hasCalleeId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'calleeId' field.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder clearCalleeId() {
      calleeId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder setPrice(java.nio.ByteBuffer value) {
      validate(fields()[6], value);
      this.price = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder clearPrice() {
      price = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[7], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
     * Gets the value of the 'orderStatus' field.
      * @return The value.
      */
    public com.example.kafka.avro.model.OrderStatus getOrderStatus() {
        return orderStatus;
    }


    /**
     * Sets the value of the 'orderStatus' field.
     * @param value The value of 'orderStatus'.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder setOrderStatus(com.example.kafka.avro.model.OrderStatus value) {
      validate(fields()[8], value);
        this.orderStatus = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
     * Checks whether the 'orderStatus' field has been set.
     * @return True if the 'orderStatus' field has been set, false otherwise.
      */
    public boolean hasOrderStatus() {
      return fieldSetFlags()[8];
    }


    /**
     * Clears the value of the 'orderStatus' field.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder clearOrderStatus() {
        orderStatus = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'failureMessages' field.
      * @return The value.
      */
    public java.lang.CharSequence getFailureMessages() {
      return failureMessages;
    }


    /**
      * Sets the value of the 'failureMessages' field.
      * @param value The value of 'failureMessages'.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder setFailureMessages(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.failureMessages = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'failureMessages' field has been set.
      * @return True if the 'failureMessages' field has been set, false otherwise.
      */
    public boolean hasFailureMessages() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'failureMessages' field.
      * @return This builder.
      */
    public com.example.kafka.avro.model.ResponseAvroModel.Builder clearFailureMessages() {
      failureMessages = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ResponseAvroModel build() {
      try {
        ResponseAvroModel record = new ResponseAvroModel();
          record.id = fieldSetFlags()[0] ? this.id : (java.util.UUID) defaultValue(fields()[0]);
          record.sagaId = fieldSetFlags()[1] ? this.sagaId : (java.util.UUID) defaultValue(fields()[1]);
          record.paymentId = fieldSetFlags()[2] ? this.paymentId : (java.util.UUID) defaultValue(fields()[2]);
          record.callerId = fieldSetFlags()[3] ? this.callerId : (java.util.UUID) defaultValue(fields()[3]);
          record.callId = fieldSetFlags()[4] ? this.callId : (java.util.UUID) defaultValue(fields()[4]);
          record.calleeId = fieldSetFlags()[5] ? this.calleeId : (java.util.UUID) defaultValue(fields()[5]);
        record.price = fieldSetFlags()[6] ? this.price : (java.nio.ByteBuffer) defaultValue(fields()[6]);
        record.createdAt = fieldSetFlags()[7] ? this.createdAt : (java.time.Instant) defaultValue(fields()[7]);
          record.orderStatus = fieldSetFlags()[8] ? this.orderStatus : (com.example.kafka.avro.model.OrderStatus) defaultValue(fields()[8]);
        record.failureMessages = fieldSetFlags()[9] ? this.failureMessages : (java.lang.CharSequence) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ResponseAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<ResponseAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ResponseAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<ResponseAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










