services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --loglevel debug

  # TODO master-slave(replica), event sourcing
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
    volumes:
      - postgres-data:/var/lib/postgresql/data



volumes:
  postgres-data: