
server:
  port: 8073

spring:
  application:
    name: "location-redis"
  profiles:
    active: native
#    active: git
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration # We don't need a datasource yet
  config:
    import: "optional:configserver:http://localhost:8071/" # For default and 'native' profile, config will be fetched from config server
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

#  cloud:
#    config:
#      server:
#        # native:
#          # search-locations: "classpath:/config"
#          # search-locations: "file:///Users//Documents//config"
#        git:
##          uri: "https://github.com/repo/config.git"
#          uri: "https://github.com/eazybytes/eazybytes-config.git"
#          default-label: main
#          timeout: 5
#          clone-on-start: true
#          force-pull: true



management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
