
server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: native
#    active: git
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"

#  cloud:
#    config:
#      server:
#        # native:
#          # search-locations: "classpath:/config"
#          # search-locations: "file:///Users//Documents//config"
#        git:
##          uri: "https://github.com/repo/config.git"
#          uri: "https://github.com/eazybytes/eazybytes-config.git"
#          default-label: main
#          timeout: 5
#          clone-on-start: true
#          force-pull: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
