/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.kafka.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum DriverApprovalStatus implements org.apache.avro.generic.GenericEnumSymbol<DriverApprovalStatus> {
  PENDING, APPROVED, REJECTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DriverApprovalStatus\",\"namespace\":\"com.example.kafka.avro.model\",\"symbols\":[\"PENDING\",\"APPROVED\",\"REJECTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
