apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  #  elasticsearch.yml 키
  # |-: YAML 멀티라인 문자열
  elasticsearch.yml: |-
    cluster.name: es-eats-cluster
    discovery.seed_hosts: elasticsearch-0.elasticsearch,elasticsearch-1.elasticsearch,elasticsearch-2.elasticsearch
    cluster.initial_master_nodes: elasticsearch-0,elasticsearch-1,elasticsearch-2
    
    