apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc-localhost
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-eatssearch-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
