apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc-localhost
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi

