version: '3'
services:
  dev:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    network_mode: host

  prod:
    build: .
    command: python3 app.py
    ports:
      - "8000:8000"

